name: qrcodeflutter
description: "A new Flutter project."

publish_to: 'none'  
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_contacts: ^1.1.9+2
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  qr_flutter: ^4.1.0
  screenshot: ^3.0.0
  url_launcher: ^6.3.1
  share_plus: ^11.0.0
  mobile_scanner: ^6.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^5.0.0
 
flutter:

  uses-material-design: true
 
  assets:
     - assets/images/
